paths:
  /api/products:
    get:
      summary: Obtiene un listado de todos los productos
      tags:
        - Products
      responses:
        "200":
          description: Operacion exitosa
          content:
            application/json:
              schema:
                type: object
                properties:
                  docs:
                    type: array
                    items:
                      $ref: "#components/schemas/Product"
                      
                  totaldocs:
                    type: number
                    example: 4
                  limit: 
                    type: number
                    example: 10
                  totalPages:
                    type: number
                    example: 4
                  page:
                    type: number
                    example: 2
                  pagingCounter:
                    type: number
                    example: 1
                  hasPrevPage:
                    type: boolean
                    example: false
                  hasNextPage:
                    type: boolean
                    example: true
                  prevPage:
                    type: number
                    example: null
                  nextPage:
                    type: number
                    example: 2
        "500":
          description: "Eror interno del servidor"
                  

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
          description: ID generado por mongo
        title:
          type: string
          description: nombre del producto
        price:
          type: number
          description: precio del producto
        description:
          type: string
          description: breve descripcion del producto
        thumbnail:
          type: string
          description: imagen de referencia del producto
        code:
          type: string
          description: Codigo de 6 caracteres unico del producto
        stock:
          type: number
          description: cantidad numerica del producto disponible
        status:
          type: boolean
          descripcion: estado del producto
        category:
          type: string
          description: categoria del producto
        owner:
          type: string
          description: dueño del producto. usuario que lo creó
      example:
        id: "665bcc5e62586dd771a50be9"
        title: Alfajor Havanna
        description: Alfajor de chocolate 70% cacao.
        price: 600
        thumbnail: "havanna.jpg"
        code: "abc123"
        stock: 50
        category: alfajores
        owner: admin
